### ISSUE TITLE
How to Add Relations

### ISSUE THREAD

**Issue by babbarankit** [hanpama/typeorm-cursor-connection#2]
Is it possible to add a relation and some conditions based on the join table.
Also, an option to change table alias will be a nice feature

**Comment by hanpama** [comment]
I've updated this to use queryBuilder instead of repository when `EntityConnection` is created.
You can join tables to the query builder before it is passed to `EntityConnection` constructor 😄

**Comment by hanpama** [comment]
https://github.com/hanpama/typeorm-cursor-connection/blob/master/tests/EntityConnection.test.ts#L68-L78
